name: Anchor Test
on:
  push:
    branches: ["main"]

_common-steps: &common-steps
  - name: Checkout
    uses: actions/checkout@v4
  - name: Echo from anchored steps
    run: echo "Hello from anchored steps!"

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      <<: *common-steps
      - name: Additional step in job_one
        run: echo "Hello from job_one!"

  job_two:
    runs-on: ubuntu-latest
    steps:
      <<: *common-steps
      - name: Additional step in job_two
        run: echo "Hello from job_two!"
